# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'RXSDKDemo-Public' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'RXSDK_Pure'
  pod 'RXUIKit'
  pod 'RXOSUIKit'
#  ,:path=>'~/localiOSPod/RXOSUIKit'
  pod 'RXWXSDK'
  pod 'RXAuthLoginKit'
  pod 'SDAutoLayout'
  pod 'BRPickerView','2.8.5'
  pod 'RXGoogleSDK'
  pod 'RXFacebookSDK'
  pod 'RXLineSDK'
  pod 'RXZaloSDK'
  pod 'RXTikTokSDK'
  pod 'RXSnapChatSDK'
  pod 'RXInstagramSDK'
  pod 'RXRedditSDK'
  pod 'RXPushSDK'
  pod 'RXLanguageKit'
  
  pod 'MBProgressHUD'
  pod 'Toast'
  pod 'Bolts'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
